networks:
  internal:
services:
  fe:
    build: .
    command: python app.py 
    ports:
      - target: 8080
        published: 5555
    networks:
      - internal
  be:
    image: "redis:alpine"
    networks:
      internal:
